# fly.toml app configuration file generated for dcn on 2023-09-22T13:54:01+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dcn"
primary_region = "sin"

[[vm]]
  size = "shared-cpu-1x"

[build]

[env]
  PROTOCOL_DB_HOME = "/app/protocol_db"

[[services]]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [services.concurrency]
    hard_limit = 500
    soft_limit = 200
    type = "requests"
  
  [[services.ports]]
    handlers = ["http"]
    port = "8000"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "8001"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

[[services]]
  internal_port = 3001
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 500
    soft_limit = 200
    type = "connections"
  
  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

[mounts]
  source="protocol_data"
  destination="/app/protocol_db"
